### ISSUE TITLE
Script breaks when run

### ISSUE THREAD

**Issue by cpeonepeloton** [redninja2/jamf-scripts#3]
when trying to run the script it errors out:

```
sudo python3 download_scripts.py
Traceback (most recent call last):
  File "/Users/Shared/scripts/download_scripts.py", line 132, in <module>
    main()
  File "/Users/Shared/scripts/download_scripts.py", line 102, in main
    tokenResponse = getToken()
  File "/Users/Shared/scripts/download_scripts.py", line 41, in getToken
    response = requests.request("POST", os.environ['JSS_URL'] + url, data=payload, headers=headers, auth=(os.environ['JSS_USER'], base64.b64decode(os.environ['JSS_PASSWORD'])))
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'JSS_URL'
```

**Comment by nahrens007** [comment]
Looks like the environment variable JSS_URL is not set properly. Please
read through the instructions.

**Comment by cpeonepeloton** [comment]
I actually read the instructions well, and installed requests with pip3.  This is how that portion looks like: `JSS_URL = "https://nasajpl.jamfcloud.com"`

**Comment by nahrens007** [comment]
I believe the issue is you are running the script with sudo so your user
environment variables are not used.
